## Deleted outputs

### __Impact and Frequency of Each Category For Every Hotel__



- In this workbook each word category (created in previous workbooks) is analysed for its impact on sentiment
- Each category is analysed for its frequency - this is useful to see how many times the word/category has been mentioned in a review
- Do this for every hotel and save in multiple spreadsheets

#### __Output__ 
- In total 5 tables are merged - frequency and impact tables for each category 
- This table is reproduced 332 times (332 hotels)


#### __Process__

- __1a) Positive category frequency - pivot table looking at the number of times the category has been mentioned in the review__
- __1b) Negative category freqwuency__

- __2) Create a pivot table looking at the impact of sentiment when someone has mentioned a specific word in the review__
- An average score was calculated for the reviews where a category was mentioned in the review
- Here we can analyse the sentiment impact of each word category for each hotel (333) 
- We can do this by creating a pivot table between the binary field, then export each table into multiple excel spread sheets

In [ ]:
import numpy as np
import pandas as pd 
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
import os
import json
import re
import numpy as np
import pandas as pd
import networkx as nx
from collections import Counter
from collections import defaultdict
from nltk.stem import WordNetLemmatizer

In [ ]:
df = pd.read_csv('Food_review_with_masterlist.csv')

In [ ]:
df.info()

In [ ]:
# Creatre a field that only has one variable, so it can be grouped into one
df['GroupBy'] = df['Rating'].replace(1,0)

In [ ]:
def count(values):
    return values.count()

# add count to find the number of values
Pos_table = pd.pivot_table(df, 
                           
                       index = ['GroupBy'],
                           
                       values = ['Pos_breakfast', 'Pos_Food', 'Pos_restaurant', 'Pos_coffee_tea', 'Pos_buffet', 
                                 'Pos_cooked', 'Pos_menu', 'Pos_Choices', 'Pos_diet', 'Pos_eating', 'Pos_plates_cups', 'Pos_bacon',
                                  'Pos_toast','Pos_eggs','Pos_juice','Pos_sausages','Pos_milk','Pos_fruit','Pos_croissants','Pos_beans',
                                 'Pos_mushrooms','Pos_tomatoes', 'Pos_Location','Pos_Staff','Pos_Arrival_experience','Pos_Facilities',
                           'Pos_Loyality','Pos_Value','Pos_Room','Pos_Bathroom','Pos_Bed','Pos_Furniture',
                           'Pos_Room facilities','Pos_Room Entertainment','Pos_Cleanliness','Pos_Technology'] ,
                           
                       aggfunc ={'Pos_breakfast':sum, 'Pos_Food_Combined':sum,'Pos_restaurant':sum, 'Pos_coffee_tea':sum, 'Pos_buffet':sum, 
                                 'Pos_cooked':sum, 'Pos_menu':sum, 'Pos_Choices':sum, 'Pos_diet':sum, 'Pos_eating':sum, 'Pos_plates_cups':sum,'Pos_bacon':sum,
                                 'Pos_toast':sum,'Pos_eggs':sum,'Pos_juice':sum,'Pos_sausages':sum,'Pos_milk':sum,'Pos_fruit':sum,'Pos_croissants':sum,
                                 'Pos_beans':sum,'Pos_mushrooms':sum,'Pos_tomatoes':sum,'Pos_Location':sum,'Pos_Staff':sum,'Pos_Arrival_experience':sum,'Pos_Facilities':sum,'Pos_Food':sum,
                           'Pos_Loyality':sum,'Pos_Value':sum,'Pos_Room':sum,'Pos_Bathroom':sum,'Pos_Bed':sum,'Pos_Furniture':sum,
                           'Pos_Room facilities':sum,'Pos_Room Entertainment':sum,'Pos_Cleanliness':sum,'Pos_Technology':sum, 'GroupBy':count})




Pos_table.rename(columns = {'GroupBy': 'Amount'}, inplace = True)
Pos_table = Pos_table.reset_index()
Pos_table

In [ ]:
# neaten up a table and return the values as a transposed table
def Transpose_table(x,name):
    x = x.rename(columns=lambda x: x.replace('Pos_', ''))
    x = x.rename(columns=lambda x: x.replace('Neg_', ''))
    x = x.rename(columns=lambda x: x.replace('neg_', ''))
    x = x.rename(columns=lambda x: x.replace('%', ''))
    x = x.T
    x = x.reset_index()
    x.rename(columns={'index': 'Category'}, inplace=True)
    x.rename(columns={0: name}, inplace=True)
    x['Category'] = x['Category'].str.capitalize()
    x['Category'] = x['Category'].replace('Plates_cups', 'Plates & Cups').replace('Coffee_tea', 
                                                                            'Coffee & Tea').replace('Diet', 'Vegetarian & Vegan').replace('%', '').replace('Loyality', 'Loyalty')
    return x

In [ ]:
def count(values):
    return values.count()

# add count to find the number of values
neg_table = pd.pivot_table(df, 
                           
                       index = ['GroupBy'],
                           
                       values = ['Neg_breakfast', 'Neg_Food', 'Neg_Food_Combined','Neg_restaurant', 'Neg_coffee_tea', 'Neg_buffet', 
                                 'Neg_cooked', 'Neg_menu', 'Neg_Choices', 'Neg_diet', 'Neg_eating', 'Neg_plates_cups', 'Neg_bacon',
                                  'Neg_toast','Neg_eggs','Neg_juice','Neg_sausages','Neg_milk','Neg_fruit','Neg_croissants','Neg_beans',
                                 'Neg_mushrooms','Neg_tomatoes', 'neg_Location','neg_Staff','neg_Arrival_experience','neg_Facilities','neg_Food',
                           'neg_Loyality','neg_Value','neg_Room','neg_Bathroom','neg_Bed','neg_Furniture',
                           'neg_Room facilities','neg_Room Entertainment','neg_Cleanliness','neg_Technology'] ,
                           
                       aggfunc ={'Neg_breakfast':sum, 'Neg_Food':sum, 'Neg_Food_Combined':sum,'Neg_restaurant':sum, 'Neg_coffee_tea':sum, 'Neg_buffet':sum, 
                                 'Neg_cooked':sum, 'Neg_menu':sum, 'Neg_Choices':sum, 'Neg_diet':sum, 'Neg_eating':sum, 'Neg_plates_cups':sum,'Neg_bacon':sum,
                                 'Neg_toast':sum,'Neg_eggs':sum,'Neg_juice':sum,'Neg_sausages':sum,'Neg_milk':sum,'Neg_fruit':sum,'Neg_croissants':sum,
                                 'Neg_beans':sum,'Neg_mushrooms':sum,'Neg_tomatoes':sum,'neg_Location':sum,'neg_Staff':sum,'neg_Arrival_experience':sum,'neg_Facilities':sum,
                           'neg_Loyality':sum,'neg_Value':sum,'neg_Room':sum,'neg_Bathroom':sum,'neg_Bed':sum,'neg_Furniture':sum,
                           'neg_Room facilities':sum,'neg_Room Entertainment':sum,'neg_Cleanliness':sum,'neg_Technology':sum,'GroupBy':count})




neg_table.rename(columns = {'GroupBy': 'Amount'}, inplace = True)
neg_table = neg_table.reset_index()

In [ ]:
neg_table.head()

In [ ]:
def pos_table(df):
    pos_table = pd.pivot_table(df, index = ['GroupBy'],
                       
                       values = ['Pos_breakfast', 'Pos_Food', 'Pos_Food_Combined', 'Pos_restaurant', 'Pos_coffee_tea', 'Pos_buffet', 
                                 'Pos_cooked', 'Pos_menu', 'Pos_Choices', 'Pos_diet', 'Pos_eating', 'Pos_plates_cups', 'Pos_bacon',
                                  'Pos_toast','Pos_eggs','Pos_juice','Pos_sausages','Pos_milk','Pos_fruit','Pos_croissants','Pos_beans',
                                 'Pos_mushrooms','Pos_tomatoes', 'Pos_Location','Pos_Staff','Pos_Arrival_experience','Pos_Facilities',
                           'Pos_Loyality','Pos_Value','Pos_Room','Pos_Bathroom','Pos_Bed','Pos_Furniture',
                           'Pos_Room facilities','Pos_Room Entertainment','Pos_Cleanliness','Pos_Technology'] ,
                           
                       aggfunc ={'Pos_breakfast':sum, 'Pos_Food_Combined':sum,'Pos_restaurant':sum, 'Pos_coffee_tea':sum, 'Pos_buffet':sum, 
                                 'Pos_cooked':sum, 'Pos_menu':sum, 'Pos_Choices':sum, 'Pos_diet':sum, 'Pos_eating':sum, 'Pos_plates_cups':sum,'Pos_bacon':sum,
                                 'Pos_toast':sum,'Pos_eggs':sum,'Pos_juice':sum,'Pos_sausages':sum,'Pos_milk':sum,'Pos_fruit':sum,'Pos_croissants':sum,
                                 'Pos_beans':sum,'Pos_mushrooms':sum,'Pos_tomatoes':sum,'Pos_Location':sum,'Pos_Staff':sum,'Pos_Arrival_experience':sum,'Pos_Facilities':sum,'Pos_Food':sum,
                           'Pos_Loyality':sum,'Pos_Value':sum,'Pos_Room':sum,'Pos_Bathroom':sum,'Pos_Bed':sum,'Pos_Furniture':sum,
                           'Pos_Room facilities':sum,'Pos_Room Entertainment':sum,'Pos_Cleanliness':sum,'Pos_Technology':sum, 'GroupBy':count})



    pos_table.rename(columns = {'GroupBy': 'Amount'}, inplace = True)
    pos_table = pos_table.reset_index()
    x = pos_table.drop(['GroupBy'], axis = 1)
    pos_table = pos_table.drop(['GroupBy'], axis = 1)
    pos_table['Pos_breakfast%'] = pos_table['Pos_breakfast']/ pos_table['Amount']*100
    pos_table['Pos_breakfast%'] = pos_table['Pos_breakfast%'].round(2)
    pos_table['Pos_Food%'] = pos_table['Pos_Food']/ pos_table['Amount']*100
    pos_table['Pos_Food%'] = pos_table['Pos_Food%'].round(2)
    pos_table['Pos_Food_Combined%'] = pos_table['Pos_Food_Combined']/ pos_table['Amount']*100
    pos_table['Pos_Food_Combined%'] = pos_table['Pos_Food_Combined%'].round(2)
    pos_table['Pos_restaurant%'] = pos_table['Pos_restaurant']/ pos_table['Amount']*100
    pos_table['Pos_restaurant%'] = pos_table['Pos_restaurant%'].round(2)
    pos_table['Pos_coffee_tea%'] = pos_table['Pos_coffee_tea']/ pos_table['Amount']*100
    pos_table['Pos_coffee_tea%'] = pos_table['Pos_coffee_tea%'].round(2)
    pos_table['Pos_buffet%'] = pos_table['Pos_buffet']/ pos_table['Amount']*100
    pos_table['Pos_buffet%'] = pos_table['Pos_buffet%'].round(2)
    pos_table['Pos_cooked%'] = pos_table['Pos_cooked']/ pos_table['Amount']*100
    pos_table['Pos_cooked%'] = pos_table['Pos_cooked%'].round(2)
    pos_table['Pos_menu%'] = pos_table['Pos_menu']/ pos_table['Amount']*100
    pos_table['Pos_menu%'] = pos_table['Pos_menu%'].round(2)
    pos_table['Pos_Choices%'] = pos_table['Pos_Choices']/ pos_table['Amount']*100
    pos_table['Pos_Choices%'] = pos_table['Pos_Choices%'].round(2)
    pos_table['Pos_diet%'] = pos_table['Pos_diet']/ pos_table['Amount']*100
    pos_table['Pos_diet%'] = pos_table['Pos_diet%'].round(2)
    pos_table['Pos_eating%'] = pos_table['Pos_eating']/ pos_table['Amount']*100
    pos_table['Pos_eating%'] = pos_table['Pos_eating%'].round(2)
    pos_table['Pos_plates_cups%'] = pos_table['Pos_plates_cups']/ pos_table['Amount']*100
    pos_table['Pos_plates_cups%'] = pos_table['Pos_plates_cups%'].round(2)
    pos_table['Pos_bacon%'] = pos_table['Pos_bacon']/ pos_table['Amount']*100
    pos_table['Pos_bacon%'] = pos_table['Pos_bacon%'].round(2)
    pos_table['Pos_toast%'] = pos_table['Pos_toast']/ pos_table['Amount']*100
    pos_table['Pos_toast%'] = pos_table['Pos_toast%'].round(2)
    pos_table['Pos_eggs%'] = pos_table['Pos_eggs']/ pos_table['Amount']*100
    pos_table['Pos_eggs%'] = pos_table['Pos_eggs%'].round(2)
    pos_table['Pos_juice%'] = pos_table['Pos_juice']/ pos_table['Amount']*100
    pos_table['Pos_juice%'] = pos_table['Pos_juice%'].round(2)
    pos_table['Pos_sausages%'] = pos_table['Pos_sausages']/ pos_table['Amount']*100
    pos_table['Pos_sausages%'] = pos_table['Pos_sausages%'].round(2)
    pos_table['Pos_milk%'] = pos_table['Pos_milk']/ pos_table['Amount']*100
    pos_table['Pos_milk%'] = pos_table['Pos_milk%'].round(2)
    pos_table['Pos_croissants%'] = pos_table['Pos_croissants']/ pos_table['Amount']*100
    pos_table['Pos_croissants%'] = pos_table['Pos_croissants%'].round(2)
    pos_table['Pos_fruit%'] = pos_table['Pos_fruit']/ pos_table['Amount']*100
    pos_table['Pos_fruit%'] = pos_table['Pos_fruit%'].round(2)
    pos_table['Pos_beans%'] = pos_table['Pos_beans']/ pos_table['Amount']*100
    pos_table['Pos_beans%'] = pos_table['Pos_beans%'].round(2)
    pos_table['Pos_mushrooms%'] = pos_table['Pos_mushrooms']/ pos_table['Amount']*100
    pos_table['Pos_mushrooms%'] = pos_table['Pos_mushrooms%'].round(2)
    pos_table['Pos_tomatoes%'] = pos_table['Pos_tomatoes']/ pos_table['Amount']*100
    pos_table['Pos_tomatoes%'] = pos_table['Pos_tomatoes%'].round(2)
    pos_table['Bathroom%'] = pos_table['Pos_Bathroom']/ pos_table['Amount']*100
    pos_table['Bathroom%'] = pos_table['Bathroom%'].round(2)
    pos_table['Bed%'] = pos_table['Pos_Bed']/ pos_table['Amount']*100
    pos_table['Bed%'] = pos_table['Bed%'].round(2)
    pos_table['Cleanliness%'] = pos_table['Pos_Cleanliness']/ pos_table['Amount']*100
    pos_table['Cleanliness%'] = pos_table['Cleanliness%'].round(2)
    pos_table['Facilities%'] = pos_table['Pos_Facilities']/ pos_table['Amount']*100
    pos_table['Facilities%'] = pos_table['Facilities%'].round(2)
    pos_table['Furniture%'] = pos_table['Pos_Furniture']/ pos_table['Amount']*100
    pos_table['Furniture%'] = pos_table['Furniture%'].round(2)

    pos_table['Location%'] = pos_table['Pos_Location']/ pos_table['Amount']*100
    pos_table['Location%'] = pos_table['Location%'].round(2)

    pos_table['Loyality%'] = pos_table['Pos_Loyality']/ pos_table['Amount']*100
    pos_table['Loyality%'] = pos_table['Loyality%'].round(2)
                                                
    pos_table['Arrival_experience%'] = pos_table['Pos_Arrival_experience']/ pos_table['Amount']*100
    pos_table['Arrival_experience%'] = pos_table['Arrival_experience%'].round(2)

    pos_table['Room%'] = pos_table['Pos_Room']/ pos_table['Amount']*100
    pos_table['Room%'] = pos_table['Room%'].round(2)
    pos_table['Room Entertainment%'] = pos_table['Pos_Room Entertainment']/ pos_table['Amount']*100
    pos_table['Room Entertainment%'] = pos_table['Room Entertainment%'].round(2)

    pos_table['Room facilities%'] = pos_table['Pos_Room facilities']/ pos_table['Amount']*100
    pos_table['Room facilities%'] = pos_table['Room facilities%'].round(2)

    pos_table['Staff%'] = pos_table['Pos_Staff']/ pos_table['Amount']*100
    pos_table['Staff%'] = pos_table['Staff%'].round(2)

    pos_table['Value%'] = pos_table['Pos_Value']/ pos_table['Amount']*100
    pos_table['Value%'] = pos_table['Value%'].round(2)

    pos_table['Technology%'] = pos_table['Pos_Technology']/ pos_table['Amount']*100
    pos_table['Technology%'] = pos_table['Technology%'].round(2)

    Pos_breakfast_to_Pos_tomatoes = pos_table.loc[:, 'Pos_breakfast%':'Technology%']
    
    return pd.merge(Transpose_table(x, '# of Reviews Positively talking about category'),
                  Transpose_table(Pos_breakfast_to_Pos_tomatoes, '% of Reviews Positively talking about category'), on=['Category'], how='inner')

In [ ]:
pos_table(df)

In [ ]:
def neg_table(df):

    neg_table = pd.pivot_table(df, 
                           
                       index = ['GroupBy'],
                       values = ['Neg_breakfast', 'Neg_Food', 'Neg_Food_Combined','Neg_restaurant', 'Neg_coffee_tea', 'Neg_buffet', 
                                 'Neg_cooked', 'Neg_menu', 'Neg_Choices', 'Neg_diet', 'Neg_eating', 'Neg_plates_cups', 'Neg_bacon',
                                  'Neg_toast','Neg_eggs','Neg_juice','Neg_sausages','Neg_milk','Neg_fruit','Neg_croissants','Neg_beans',
                                 'Neg_mushrooms','Neg_tomatoes', 'neg_Location','neg_Staff','neg_Arrival_experience','neg_Facilities','neg_Food',
                           'neg_Loyality','neg_Value','neg_Room','neg_Bathroom','neg_Bed','neg_Furniture',
                           'neg_Room facilities','neg_Room Entertainment','neg_Cleanliness','neg_Technology'] ,
                           
                       aggfunc ={'Neg_breakfast':sum, 'Neg_Food':sum, 'Neg_Food_Combined':sum,'Neg_restaurant':sum, 'Neg_coffee_tea':sum, 'Neg_buffet':sum, 
                                 'Neg_cooked':sum, 'Neg_menu':sum, 'Neg_Choices':sum, 'Neg_diet':sum, 'Neg_eating':sum, 'Neg_plates_cups':sum,'Neg_bacon':sum,
                                 'Neg_toast':sum,'Neg_eggs':sum,'Neg_juice':sum,'Neg_sausages':sum,'Neg_milk':sum,'Neg_fruit':sum,'Neg_croissants':sum,
                                 'Neg_beans':sum,'Neg_mushrooms':sum,'Neg_tomatoes':sum,'neg_Location':sum,'neg_Staff':sum,'neg_Arrival_experience':sum,'neg_Facilities':sum,
                           'neg_Loyality':sum,'neg_Value':sum,'neg_Room':sum,'neg_Bathroom':sum,'neg_Bed':sum,'neg_Furniture':sum,
                           'neg_Room facilities':sum,'neg_Room Entertainment':sum,'neg_Cleanliness':sum,'neg_Technology':sum,'GroupBy':count})



    neg_table.rename(columns = {'GroupBy': 'Amount'}, inplace = True)
    neg_table = neg_table.reset_index()
    x = neg_table.drop(['GroupBy'], axis = 1)
    neg_table = neg_table.drop(['GroupBy'], axis = 1)
    neg_table['Neg_breakfast%'] = neg_table['Neg_breakfast']/ neg_table['Amount']*100
    neg_table['Neg_breakfast%'] = neg_table['Neg_breakfast%'].round(2)
    neg_table['Neg_Food%'] = neg_table['Neg_Food']/ neg_table['Amount']*100
    neg_table['Neg_Food%'] = neg_table['Neg_Food%'].round(2)
    neg_table['Neg_Food_Combined%'] = neg_table['Neg_Food_Combined']/ neg_table['Amount']*100
    neg_table['Neg_Food_Combined%'] = neg_table['Neg_Food_Combined%'].round(2)
    neg_table['Neg_restaurant%'] = neg_table['Neg_restaurant']/ neg_table['Amount']*100
    neg_table['Neg_restaurant%'] = neg_table['Neg_restaurant%'].round(2)
    neg_table['Neg_coffee_tea%'] = neg_table['Neg_coffee_tea']/ neg_table['Amount']*100
    neg_table['Neg_coffee_tea%'] = neg_table['Neg_coffee_tea%'].round(2)
    neg_table['Neg_buffet%'] = neg_table['Neg_buffet']/ neg_table['Amount']*100
    neg_table['Neg_buffet%'] = neg_table['Neg_buffet%'].round(2)
    neg_table['Neg_cooked%'] = neg_table['Neg_cooked']/ neg_table['Amount']*100
    neg_table['Neg_cooked%'] = neg_table['Neg_cooked%'].round(2)
    neg_table['Neg_menu%'] = neg_table['Neg_menu']/ neg_table['Amount']*100
    neg_table['Neg_menu%'] = neg_table['Neg_menu%'].round(2)
    neg_table['Neg_Choices%'] = neg_table['Neg_Choices']/ neg_table['Amount']*100
    neg_table['Neg_Choices%'] = neg_table['Neg_Choices%'].round(2)
    neg_table['Neg_diet%'] = neg_table['Neg_diet']/ neg_table['Amount']*100
    neg_table['Neg_diet%'] = neg_table['Neg_diet%'].round(2)
    neg_table['Neg_eating%'] = neg_table['Neg_eating']/ neg_table['Amount']*100
    neg_table['Neg_eating%'] = neg_table['Neg_eating%'].round(2)
    neg_table['Neg_plates_cups%'] = neg_table['Neg_plates_cups']/ neg_table['Amount']*100
    neg_table['Neg_plates_cups%'] = neg_table['Neg_plates_cups%'].round(2)
    neg_table['Neg_bacon%'] = neg_table['Neg_bacon']/ neg_table['Amount']*100
    neg_table['Neg_bacon%'] = neg_table['Neg_bacon%'].round(2)
    neg_table['Neg_toast%'] = neg_table['Neg_toast']/ neg_table['Amount']*100
    neg_table['Neg_toast%'] = neg_table['Neg_toast%'].round(2)
    neg_table['Neg_eggs%'] = neg_table['Neg_eggs']/ neg_table['Amount']*100
    neg_table['Neg_eggs%'] = neg_table['Neg_eggs%'].round(2)
    neg_table['Neg_juice%'] = neg_table['Neg_juice']/ neg_table['Amount']*100
    neg_table['Neg_juice%'] = neg_table['Neg_juice%'].round(2)
    neg_table['Neg_sausages%'] = neg_table['Neg_sausages']/ neg_table['Amount']*100
    neg_table['Neg_sausages%'] = neg_table['Neg_sausages%'].round(2)
    neg_table['Neg_milk%'] = neg_table['Neg_milk']/ neg_table['Amount']*100
    neg_table['Neg_milk%'] = neg_table['Neg_milk%'].round(2)
    neg_table['Neg_croissants%'] = neg_table['Neg_croissants']/ neg_table['Amount']*100
    neg_table['Neg_croissants%'] = neg_table['Neg_croissants%'].round(2)
    neg_table['Neg_fruit%'] = neg_table['Neg_fruit']/ neg_table['Amount']*100
    neg_table['Neg_fruit%'] = neg_table['Neg_fruit%'].round(2)
    neg_table['Neg_beans%'] = neg_table['Neg_beans']/ neg_table['Amount']*100
    neg_table['Neg_beans%'] = neg_table['Neg_beans%'].round(2)
    neg_table['Neg_mushrooms%'] = neg_table['Neg_mushrooms']/ neg_table['Amount']*100
    neg_table['Neg_mushrooms%'] = neg_table['Neg_mushrooms%'].round(2)
    neg_table['Neg_tomatoes%'] = neg_table['Neg_tomatoes']/ neg_table['Amount']*100
    neg_table['Neg_tomatoes%'] = neg_table['Neg_tomatoes%'].round(2)
    neg_table['Bathroom%'] = neg_table['neg_Bathroom']/ neg_table['Amount']*100
    neg_table['Bathroom%'] = neg_table['Bathroom%'].round(2)


    neg_table['Bed%'] = neg_table['neg_Bed']/ neg_table['Amount']*100
    neg_table['Bed%'] = neg_table['Bed%'].round(2)



    neg_table['Cleanliness%'] = neg_table['neg_Cleanliness']/ neg_table['Amount']*100
    neg_table['Cleanliness%'] = neg_table['Cleanliness%'].round(2)



    neg_table['Facilities%'] = neg_table['neg_Facilities']/ neg_table['Amount']*100
    neg_table['Facilities%'] = neg_table['Facilities%'].round(2)


    neg_table['Furniture%'] = neg_table['neg_Furniture']/ neg_table['Amount']*100
    neg_table['Furniture%'] = neg_table['Furniture%'].round(2)



    neg_table['Location%'] = neg_table['neg_Location']/ neg_table['Amount']*100
    neg_table['Location%'] = neg_table['Location%'].round(2)



    neg_table['Loyality%'] = neg_table['neg_Loyality']/ neg_table['Amount']*100
    neg_table['Loyality%'] = neg_table['Loyality%'].round(2)


    neg_table['Arrival_experience%'] = neg_table['neg_Arrival_experience']/ neg_table['Amount']*100
    neg_table['Arrival_experience%'] = neg_table['Arrival_experience%'].round(2)



    neg_table['Room%'] = neg_table['neg_Room']/ neg_table['Amount']*100
    neg_table['Room%'] = neg_table['Room%'].round(2)



    neg_table['Room Entertainment%'] = neg_table['neg_Room Entertainment']/ neg_table['Amount']*100
    neg_table['Room Entertainment%'] = neg_table['Room Entertainment%'].round(2)



    neg_table['Room facilities%'] = neg_table['neg_Room facilities']/ neg_table['Amount']*100
    neg_table['Room facilities%'] = neg_table['Room facilities%'].round(2)



    neg_table['Staff%'] = neg_table['neg_Staff']/ neg_table['Amount']*100
    neg_table['Staff%'] = neg_table['Staff%'].round(2)



    neg_table['Value%'] = neg_table['neg_Value']/ neg_table['Amount']*100
    neg_table['Value%'] = neg_table['Value%'].round(2)


    neg_table['Technology%'] = neg_table['neg_Technology']/ neg_table['Amount']*100
    neg_table['Technology%'] = neg_table['Technology%'].round(2)


    Neg_breakfast_to_Neg_tomatoes = neg_table.loc[:, 'Neg_breakfast%':]
    #T_table(Neg_breakfast_to_Neg_tomatoes, '% of Reviews Positively talking about category')
    #pd.merge(Transpose_table(x, '# of Reviews Negatively talking about category'),Transpose_table(Neg_breakfast_to_Neg_tomatoes, '% of Reviews Negatively talking about category'), on=['Category'], how='inner')
    return pd.merge(Transpose_table(x, '# of Reviews Negatively talking about category'),Transpose_table(Neg_breakfast_to_Neg_tomatoes, '% of Reviews Negatively talking about category'), on=['Category'], how='inner')

In [ ]:
neg_table(df)

__________________________________________________________________________________________________________________________________________

### 2) Create a pivot table looking at the impact of sentiment when someone has mentioned a specific word in the review

- An average score was calculated for the reviews where a category was mentioned in the review
- Here we can analyse the sentiment impact of each word category for each brand
- We can do this by creating a pivot table between the binary field

__________________________________________________________________________________________________________________________________________

In [ ]:
#Now lets create a function for the above code

def PT(df, x):
    table= pd.pivot_table(df, index = [x],
                       values = ['sentiment'], aggfunc ={'sentiment':np.mean})
    table = table.reset_index()
    table = table[table[x] == 1]
    table[x] = table[x] * table['sentiment']
    return table[[x]]

__________________________________________________________________________________________________________________________________________

### Create a table for Negative and Positive, combine and find the difference

- Merge the frequency table with the impact table

__________________________________________________________________________________________________________________________________________

In [ ]:
# Create a function for the above code
def neg_concat_pt_tables(df):
    lst = df.loc[:, 'Neg_Food': 'neg_Technology']
    lst = lst.columns
    table = pd.concat([PT(df, x) for x in lst], axis = 1)
    table = table.rename(columns=lambda x: x.replace('Neg_', ''))
    table = table.rename(columns=lambda x: x.replace('neg_', ''))
    table = table.transpose()
    table = table.reset_index()
    table.rename(columns={'index': 'Category'}, inplace=True)
    table.rename(columns={1: 'Where commented negatively about category'}, inplace=True)
    return table

def pos_concat_pt_tables(df):
    lst = df.loc[:, 'Pos_Food':'Pos_Technology']
    lst = lst.columns
    table = pd.concat([PT(df, x) for x in lst], axis = 1)
    table = table.rename(columns=lambda x: x.replace('Pos_', ''))
    table = table.transpose()
    table = table.reset_index()
    table.rename(columns={'index': 'Category'}, inplace=True)
    table.rename(columns={1: 'Where commented positively about category'}, inplace=True)
    return table

In [ ]:
def concat_pt_tables(df):
    
    #Merge above dataframes
    x = pd.merge(neg_concat_pt_tables(df) ,pos_concat_pt_tables(df), on=['Category'], how='outer')
    
    # neaten up category values
    x['Category'] = x['Category'].str.capitalize()
    x['Category'] = x['Category'].replace('Plates_cups', 'Plates & Cups').replace('Coffee_tea', 'Coffee & Tea').replace('Diet', 'Vegetarian & Vegan').replace('Loyality', 'Loyalty')
    
    # problems with just subtracting columns - therefore used pandas diff() function and renamed the columns and joined
    test = x.diff(axis=1)
    test.rename(columns={'Where commented positively about category': 'Difference'}, inplace=True)
    
    # Concat difference value to impact table
    test = test[['Difference']]
    concat_difference_table = pd.concat([x,test], axis = 1)
    
    # Merge Impact tabe with positive frequency table
    Positive_and_impact = pd.merge(pos_table(df), concat_difference_table, on=['Category'], how='inner')
    
    # Merge Impact tabe with negative frequency table
    impact_and_freq = pd.merge(neg_table(df), Positive_and_impact, on=['Category'], how='inner')
    
    # Calculate Total Mention
    impact_and_freq['Total Mentions'] = impact_and_freq['# of Reviews Negatively talking about category'] + impact_and_freq['# of Reviews Positively talking about category']
    impact_and_freq = impact_and_freq.drop_duplicates()

    #return table with most mentioned category first
    return impact_and_freq.sort_values('Total Mentions', ascending=False)

In [102]:
# Exaxample taken from another workbook

## This is missing total mentions for negative and positive reviews
test = concat_pt_tables(df)
test

,Category,Where commented negatively about category,Where commented positively about category,Difference
0,Food,4.545955,4.086965,-0.458990
1,Choices,4.634182,4.305918,-0.328265
2,Eating,4.556962,4.074733,-0.482229
3,Plates & Cups,4.378947,4.024390,-0.354557
4,Cooked,4.564103,4.272993,-0.291110
5,Menu,4.497191,4.311358,-0.185833
6,Coffee & Tea,4.509929,4.226109,-0.283820
7,Restaurant,4.468515,4.127138,-0.341377
8,Buffet,4.566340,4.217949,-0.348391
9,Vegetarian & Vegan,4.551282,4.301587,-0.249695
10,Breakfast,4.507581,4.193656,-0.313926
11,Tomatoes,4.586207,4.510373,-0.075833
12,Toast,4.341880,4.241993,-0.099887
13,Mushrooms,4.384615,4.442724,0.058109
14,Beans,4.318841,4.182119,-0.136721
15,Croissants,4.456349,4.200820,-0.255530
16,Fruit,4.543269,4.231461,-0.311809
17,Milk,4.543103,4.293893,-0.249210
18,Sausages,4.475610,4.253506,-0.222104
19,Juice,4.531250,4.144928,-0.386322
20,Eggs,4.407674,4.272356,-0.135318
21,Bacon,4.331818,4.218848,-0.112970

__________________________________________________________________________________________________________________________________________

#### Note

- Now lets loop the function for all the dataframes and save them to multiple excel sheets
__________________________________________________________________________________________________________________________________________

In [ ]:
# function to create an excel file with multiple sheets
def dfs_tabs(df_list, sheet_list, file_name):
    
    '''function to create an excel file with multiple sheets '''
    
    writer = pd.ExcelWriter(file_name,engine='xlsxwriter')   

    for dataframe, sheet in zip(df_list, sheet_list):
        dataframe.to_excel(writer, sheet_name=sheet, startrow=0 , startcol=0)   
        
    writer.save()

In [ ]:
# create the list of hotels
hotel_list = df.groupby(['Hotel Code']).sum()
hotel_list = hotel_list.reset_index()
hotel_list = hotel_list['Hotel Code']
hotel_list = list(str(e) for e in hotel_list)

In [ ]:
# create a dataframe for each hotel
def hotellist(x):
    return df[df['Hotel Code'] == x]

In [ ]:
# Create a dataframe for each hotel in the hotel list
dfs = [hotellist(x) for x in hotel_list]

# List comprehension using the above concat pivot table function for each dataframe
dfs = [concat_pt_tables(x) for x in dfs]

# Perform the multiple excel sheet function on the selected dataframes
dfs_tabs(dfs, hotel_list, 'Impact_and_freq.xlsx')

__________________________________________________________________________________________________________________________________________

#### Output

- An excel spreadsheet with 332 sheets, showing the sentiment impact of each category
__________________________________________________________________________________________________________________________________________

In [ ]:
print(df[['Hotel Code']].nunique())